### PR TITLE
Add remove/clear controls and a better preview

### PR DESCRIPTION
**Pull request by nervetattoo**
Halla Fredrik ;)

Well I guess I ended up using your plugin somewhere and found it lacking some crucial features to deal with modifying tables.
This adds the ability to:

- Remove a specific row
- Remove a specific column (across all rows)
- Remove all rows & columns
- Empty all cell values
- A better preview

See screens for what it basically adds:

Screen Shot 2020-03-22 at 15 05 10
Screen Shot 2020-03-22 at 15 04 40

### CODE REVIEW

**Comment by nervetattoo** [comment]
Oh I guess this fixes #3

**Comment by masives** [comment]
@nervetattoo is there a possibilty that this will get merged and released? This is the only sanity table plugin that's compatible with gatsby

**Comment by fredjens** [comment]
@nervetattoo Sorry, did not see this! Hi btw! 🙂

**Comment by nervetattoo** [comment]
Better late than never 🌟

**Pull request merged**
